version: "2"

run:
  timeout: 5m

linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 40  # Raised: deserializers are inherently complex
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes:
      - github.com/smnsjas/go-psrpcore
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - ifElseChain
      - octalLiteral

linters:
  enable:
    - govet
    - revive
    - gosec
    - gocyclo
    - unconvert
    - goconst
    - misspell
    - lll
    - unparam
    - ineffassign
    - staticcheck
  disable:
    - errcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude lll for test files (XML test data is inherently long)
    - path: "(.+)_test\\.go"
      linters:
        - lll
    # Exclude lll for cmd/psrp-test (test helper with long command strings)
    - path: "cmd/psrp-test/"
      linters:
        - lll
